-- Add columns to Docentes table
ALTER TABLE public.docentes
ADD COLUMN IF NOT EXISTS cpf VARCHAR(20),
    ADD COLUMN IF NOT EXISTS email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS telefone VARCHAR(20),
    ADD COLUMN IF NOT EXISTS whatsapp BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS nivel VARCHAR(50),
    ADD COLUMN IF NOT EXISTS area_formacao VARCHAR(255),
    ADD COLUMN IF NOT EXISTS vinculo VARCHAR(50);